blog/urls.py
from django.urls import path, re_path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

grit/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from graphene_django.views import GraphQLView
from django.views.generic import TemplateView
# from grit.schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('articles/', include("blog.urls", namespace='blog')),
    path('lookbook/', include("lookbook.urls", namespace='lookbook')),
    # path('graphql', GraphQLView.as_view(graphiql=True, schema=schema)),
    path('', include("locator.urls", namespace='locator')),
    re_path(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file")
]

handler404 = 'locator.views.error.handler404'
handler500 = 'locator.views.error.handler500'

locator/urls.py
from django.urls import path, re_path, include
from locator.views import home, search, common
from locator.views.product import product, collections
from locator.views.deals import deal as deals
from django.contrib.sitemaps.views import sitemap
from locator.sitemaps import ProductSitemap, CollectionSitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'products': ProductSitemap,
    'posts': PostSitemap,
    'collections': CollectionSitemap
}

app_name = 'locator'

urlpatterns = [
    path('', home.index, name='home'),
    path('sitemap.xml', sitemap,
            {'sitemaps': sitemaps}, name='sitemap'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('search/', search.SearchView.as_view(), name='search'),
    path('contact/', common.contact, name='contact'),
    path('brand/<slug:name>', product.branded_product, name='brands'),
    path('collections/<slug:name>/', collections.collections, name='collection'),
    path('products/<slug:name>/', product.detail_view, name='product_view'),
    path('products/', product.products_view, name='products_view'),
    path('deals/<slug:name>/', deals.offer_detail, name='offer_detail'),
    path('deals/', deals.DealsListView.as_view(), name='offer_list'),
    path('<slug:slug>/', include([
        path('', home.product_category, name='category_products'),
        path('<slug:pslug>/', home.product_details, name='product_detail'),
    ])),
]

newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

app_name = 'newsletter'

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

locator/views/common.py
from django.shortcuts import render
from locator.models import Product, Category

def contact(request):
	return render(request, 'locator/common/contact_us.html')

locator/views/error.py
from django.shortcuts import render, redirect

def handler404(request, exception):
    """ 404 Not Found Error """
    return render(request,'locator/error/404.html',{})

def handler500(request):
    """ %00 Server error """
    return render(request,'locator/error/500.html', {})

locator/views/home.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from locator.models import Product, Category
from locator.filters import ProductFilter
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page
from meta.views import Meta

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

@cache_page(CACHE_TTL)
def index(request):
    products = Product.objects.prefetch_related().all().order_by('?')[:5]
    categories = Category.published.filter(parent=None)
    meta = Meta(
        title=settings.META_SITE_TITLE,
        url=settings.META_SITE_PROTOCOL + "://" + settings.META_SITE_DOMAIN,
        description=settings.META_DESCRIPTION,
        keywords=settings.META_INCLUDE_KEYWORDS,
        use_og="true",
        use_googleplus="true",
        og_description=settings.META_DESCRIPTION,
        og_type="Article",
        extra_props={
            'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'
        },
        extra_custom_props= [
            ('http-equiv', 'Content-Type', 'text/html; charset=UTF-8'),
        ]
    )
    return render(request, 'locator/index.html', {"products": products, "categories": categories, "meta": meta})

@cache_page(CACHE_TTL)
def product_details(request, slug, pslug):
    product = get_object_or_404(Product, slug=pslug)
    latest_products = Product.objects.prefetch_related().filter(
        category_id=product.category_id).exclude(slug=pslug)[:5]

    return render(request, 'locator/product/product_details.html', {"product": product, 'latest_products': latest_products, 'meta': product.as_meta()})

@cache_page(CACHE_TTL)
def product_category(request, slug):
    try:
        category = Category.objects.select_related().get(slug=slug)
        products = None
        product_list = Product.objects.prefetch_related().order_by("?")
    except ObjectDoesNotExist:
        product_list = None
    product_filter = ProductFilter(request.GET, queryset=product_list)
    productsData = product_filter.qs

    if category.parent_id is not None:
        products = productsData.filter(category_id=category.id)

    else:
        category_ids = Category.objects.all().filter(
            id=category.id).values_list("children__id", flat=True).distinct()
        products = productsData.filter(category__in=category_ids).order_by('?')

    page = request.GET.get('page', 1)
    paginator = Paginator(products, 20)
    try:
        numbers = paginator.page(page)
    except PageNotAnInteger:
        numbers = paginator.page(1)
    except EmptyPage:
        numbers = paginator.page(paginator.num_pages)

    return render(request, 'locator/product/product_category.html', {'filter': product_filter, "products": numbers, "name": slug, "meta": category.as_meta()})

locator/views/search.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.postgres.aggregates import StringAgg
from locator.models import Product, Category
from django.views.generic.list import ListView
from locator.filters import ProductFilter
from django.shortcuts import render
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

class SearchView(ListView):
   model = Product
   template_name = 'locator/product/search_results.html'
   paginate_by = 20

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      product_list = Product.objects.all()
      product_filter = ProductFilter(self.request.GET, queryset=product_list)
      qs = product_filter.qs
      try:
          search_string = self.request.GET['q']
          query = SearchQuery(search_string)
          vector=(
              SearchVector('name',  weight='A') +
              SearchVector('description',  weight='C')
          )
          qs = qs.annotate(
              document=vector, rank=SearchRank(vector, query)
          ).filter(document=query).order_by('-rank').values()
      except KeyError:
          return Product.objects.none()

      context['products'] = qs.order_by('updated_at')
      context["path"] = search_string
      context["filter"] = product_filter
      return context

@cache_page(CACHE_TTL)
def search(request):
    product_list = Product.objects.all().order_by("?")
    product_filter = ProductFilter(request.GET, queryset=product_list)
    page = request.GET.get('page', 1)
    paginator = Paginator(product_filter.qs, 10)
    try:
        numbers = paginator.page(page)
    except PageNotAnInteger:
        numbers = paginator.page(1)
    except EmptyPage:
        numbers = paginator.page(paginator.num_pages)
    return render(request, 'locator/product/search_results.html', {'filter': product_filter, 'products':numbers})

templates/locator/product/product_banner.html
<div class="col-sm-12 mt-2">
    <a href='{% url "locator:product_detail" product.category.slug product.slug %}' title="{{product.name}}">
        <div class="card bg-light text-black">
            <img class="card-img" src="{{product.images.0}}" alt="{{product.name}}" title="{{product.name}}" alt="{{product.name}}">
            <div class="card-img-overlay" style="text-align:right;">
                <p class="card-text"><span class="banner-price">₹ {{product.price}}</span></p>
            </div>
        </div>
    </a>
</div>

templates/locator/product/product_category.html
{% extends 'locator/common/base.html' %} {% block app_title %}{{name|capfirst}}{% endblock %} {% block app_body %}
<div class="fluid-container mt-1 ml-2 mr-2">
    <div class="row m-0 jumbotron">
        <div class="col-md-12 text-center">
            <h1 class="p-2">{{name|capfirst}}</h1>
        </div>
        {% include '../common/filter.html' %}
        <div class="col-md-10">
            <div id="columns" class="columns_4 infinite-container">
                {% if products %} {% for product in products %} {% include 'locator/product/product_item_search.html' %} {% endfor %} {% else %}
                <h3> No Product matches your criteria</h3>
                {% endif %}
            </div>
            {% if products.has_next %}
            <a class="infinite-more-link pd-5" href="?page={{ products.next_page_number }}" rel="canonical"></a> {% endif %}
            <div style="text-align:center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 340 340" class="loader pd-5" style="display: none;text-align: center;">
                 <circle cx="170" cy="170" r="160" stroke="#E2007C"/>
                 <circle cx="170" cy="170" r="135" stroke="#404041"/>
                 <circle cx="170" cy="170" r="110" stroke="#E2007C"/>
                 <circle cx="170" cy="170" r="85" stroke="#404041"/>
            </svg>
        </div>
        </div>
    </div>
</div>
<script>
var infinite = new Waypoint.Infinite({
    element: $('.infinite-container')[0],
    onBeforePageLoad: function() {
        $('.loader').show();
    },
    onAfterPageLoad: function($items) {
        $('.loader').hide();
    }
});
</script>
{% endblock %}

templates/locator/product/product_details.html
{% extends 'locator/common/base.html' %} {% block app_title %}{{product.name}}{% endblock %} {% load humanize %} {% block app_body %}
<div class="fluid-container mt-1 ml-2 mr-2 pt-5">
    <div class="row pd-5">
        <div class="col-sm-6" style="text-align:center;max-height:400px;">
            <img class="img-responsive" src="{{product.images.0}}" alt="{{product.name}}" style="max-width: 89%;max-height: 350px;">
        </div>
        <div class="col-sm-6">
            <h1 itemprop="name">{{product.name}}</h1>
            <span class="price" itemprop="price">₹ {{product.price|intcomma}} <del class="ml-3" style="color: grey;">₹ {{product.old_price|intcomma}}</span>
            <div class="mt-5">
                <a class="btn pd-3 btn-card" href='{{product.store_url}}' target="_blank" rel="noopener noreferrer nofollow">Buy Now</a>
            </div><hr>
            {% spaceless %}
            {% if product.description %}
                <h3>Description</h3>
                <div class="item_description mt-3">
                {% autoescape off %} {{product.description}} {% endautoescape %}</div>
            {% endif %}
            {% endspaceless %}
        </div>
        <!-- Featured products -->
        {% if latest_products %}
        <div class="col-md-12 mt-5 pd-5 category-banner shadow-sm">
            <h3 class="ml-2">More Featured Products</h3>
            <div id="columns" class="columns_4">
                {% for product in latest_products %} {% include 'locator/product/product_item.html' %} {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/locator/product/product_item.html
{% load humanize %} {% load products %}
<figure class="infinite-item">
	<a href='{% url "locator:product_detail" product.get_category_slug product.slug %}' title="{{product.name}}" rel="canonical">
    <img src="{{product.images.0}}" alt="{{product.name}}" title="{{product.name}}">
    <figcaption name="name">{{product.name|name}}</figcaption>
    <span class="price">₹ {{product.price|intcomma}}</span>
</a>
</figure>

templates/locator/product/product_item_search.html
{% load humanize %} {% load products %}
<figure class="infinite-item">
    <a href='{% url "locator:product_view" product.slug %}' title="{{product.name}}">
    <img src="{{product.images.0}}" alt="{{product.name}}" title="{{product.name}}">
    <figcaption name="name">{{product.name|name}}</figcaption>
    <span class="price">₹ {{product.price|intcomma}}</span>
</a>
</figure>

templates/locator/product/search_results.html
{% extends 'locator/common/base.html' %} {% load widget_tweaks %} {% block app_body %}
<div class="fluid-container mt-1 ml-2 mr-2">
    <div class="row jumbotron">
        {% include '../common/filter.html' %}
        <div class="col-md-10">
            <div id="columns" class="columns_4 infinite-container">
                {% if products %} {% for product in products %} {% include 'locator/product/product_item_search.html' %} {% endfor %} {% else %}
                <h3>No Products Found</h3> {% endif %}
            </div>
            {% if products.has_next %}
            <a class="infinite-more-link pd-5" href="?page={{ filter.qs.next_page_number }}"></a> {% endif %}
            <div style="text-align:center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 340 340" class="loader pd-5" style="display: none;text-align: center;">
                 <circle cx="170" cy="170" r="160" stroke="#E2007C"/>
                 <circle cx="170" cy="170" r="135" stroke="#404041"/>
                 <circle cx="170" cy="170" r="110" stroke="#E2007C"/>
                 <circle cx="170" cy="170" r="85" stroke="#404041"/>
            </svg>
        </div>
        </div>
    </div>
</div>
<script>
var infinite = new Waypoint.Infinite({
    element: $('.infinite-container')[0],
    onBeforePageLoad: function() {
        $('.loader').show();
    },
    onAfterPageLoad: function($items) {
        $('.loader').hide();
    }
});
</script>
{% endblock %}