blog/urls.py
from django.urls import path, re_path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

grit/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from graphene_django.views import GraphQLView
from django.views.generic import TemplateView
# from grit.schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('articles/', include("blog.urls", namespace='blog')),
    path('lookbook/', include("lookbook.urls", namespace='lookbook')),
    # path('graphql', GraphQLView.as_view(graphiql=True, schema=schema)),
    path('', include("locator.urls", namespace='locator')),
    re_path(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file")
]

handler404 = 'locator.views.error.handler404'
handler500 = 'locator.views.error.handler500'

locator/urls.py
from django.urls import path, re_path, include
from locator.views import home, search, common
from locator.views.product import product, collections
from locator.views.deals import deal as deals
from django.contrib.sitemaps.views import sitemap
from locator.sitemaps import ProductSitemap, CollectionSitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'products': ProductSitemap,
    'posts': PostSitemap,
    'collections': CollectionSitemap
}

app_name = 'locator'

urlpatterns = [
    path('', home.index, name='home'),
    path('sitemap.xml', sitemap,
            {'sitemaps': sitemaps}, name='sitemap'),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('search/', search.SearchView.as_view(), name='search'),
    path('contact/', common.contact, name='contact'),
    path('brand/<slug:name>', product.branded_product, name='brands'),
    path('collections/<slug:name>/', collections.collections, name='collection'),
    path('products/<slug:name>/', product.detail_view, name='product_view'),
    path('products/', product.products_view, name='products_view'),
    path('deals/<slug:name>/', deals.offer_detail, name='offer_detail'),
    path('deals/', deals.DealsListView.as_view(), name='offer_list'),
    path('<slug:slug>/', include([
        path('', home.product_category, name='category_products'),
        path('<slug:pslug>/', home.product_details, name='product_detail'),
    ])),
]

newsletter/urls.py
from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionView,
)

app_name = 'newsletter'

urlpatterns = [
    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionView.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
]

locator/views/common.py
from django.shortcuts import render
from locator.models import Product, Category

def contact(request):
	return render(request, 'locator/common/contact_us.html')

templates/common/base.html
{% load static %} {% load category_tag %}{% load meta %}
<!DOCTYPE html>
<html lang="en">

<head {% meta_namespaces %}>
    {% include '../meta.html' %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text|Work+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet"> {% block css %} {% endblock %}
    <link rel="stylesheet" href="{% static 'css/common.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/lookbook.css' %}">
    {% block app_head %}{% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/category.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'css/bootstrap/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
</head>

<body>
    {% show_side_menu %}
    {% include './header.html' %}
    <main role="main"> {% block app_body %}{% endblock %}</main>
    {% include './footer.html' %}
    </div>
</body>
{% block javascript %} {% endblock %}

</html>

templates/common/footer.html
{% load static %}
{% load category_tag %}
<footer class="blog-footer">
    <section class="footers bg-light">
        <div class="container pt-5">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4 footers-one">
                    <div class="footers-logo">
                        <img src="{% static 'images/logo.png' %}" alt="Logo" style="width:120px;">
                    </div>
                    <div class="social-icons">
                        <a target="_blank" alt="zeshastyles facebook page" rel="noopener noreferrer" href="https://www.facebook.com/zeshastyles/"><i id="social-fb" class="fab fa-facebook-square fa-1x social"></i></a>
                        <a target="_blank" alt="zeshastyles google plus page" rel="noopener noreferrer" href="https://plus.google.com/u/0/106725238703021839319"><i id="social-fb" class="fab fa-google-plus-g fa-1x social"></i></a>
                        <a target="_blank" alt="zeshastyles twitter page" rel="noopener noreferrer" href="https://twitter.com/zeshastyles"><i id="social-fb" class="fab fa-twitter fa-1x social"></i></a>
                        <a target="_blank" alt="zeshastyles company page" rel="noopener noreferrer" href="https://www.linkedin.com/company/zeshastyles/"><i class="fab fa-linkedin-in fa-1x social"></i></a>
                        <a target="_blank" alt="zeshastyles pinterest page" rel="noopener noreferrer" href="https://in.pinterest.com/Zeshastyles/"><i class="fab fa-pinterest fa-1x social"></i></a>
                        <a target="_blank" alt="zeshastyles tumblr page" rel="noopener noreferrer" href="https://zeshastyles.tumblr.com/"><i class="fab fa-tumblr fa-1x social"></i></a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4 footers-two">
                    <h5>Category</h5>
                    {% list_categories %}
                </div>
                <div class="col-xs-12 col-sm-6 col-md-2 footers-four">
                    <h5>Fashion</h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
                        <li><a href="{% url 'newsletter:newsletter_subscribe_request' 'trending-products' %}">Newsletter</a></li>
                        <li><a href="{% url 'lookbook:home' %}">Lookbook</a></li>
                    </ul>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-2 footers-five">
                    <h5>Company </h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'locator:contact' %}">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="disclaimer bg-light border">
        <div class="container">
            <div class="row ">
                <div class="col-md-12 py-2">
                    <small>
                   Disclaimer: Element Limited is only an intermediary offering its platform to facilitate the transactions between Seller and Customer/Buyer/User and is not and cannot be a party to or control in any manner any transactions between the Seller and the Customer/Buyer/User. All the offers and discounts on this Website have been extended by various Builder(s)/Developer(s) who have advertised their products. Element is only communicating the offers and not selling or rendering any of those products or services. It neither warrants nor is it making any representations with respect to offer(s) made on the site. Element Limited shall neither be responsible nor liable to mediate or resolve any disputes or disagreements between the Customer/Buyer/User and the Seller and both Seller and Customer/Buyer/User shall settle all such disputes without involving Element Limited in any manner.
               </small>
                </div>
            </div>
        </div>
    </section>
    <section class="copyright border">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12 pt-3">
                    <p class="text-muted">© 2018 Zesha Styles Pvt. Ltd.</p>
                </div>
            </div>
        </div>
    </section>
</footer>
<script async type='text/javascript'>
    var pubID = '46354CL41816';

    (function(d, t) {
    var s = document.createElement('script');s.type = 'text/javascript';
    s.async = true;s.src = (document.location.protocol == 'https:' ? 'https://cdn0.cuelinks.com/js/' : 'http://cdn0.cuelinks.com/js/')  + 'cuelinksv1.js';
    document.getElementsByTagName('body')[0].appendChild(s);
    }());
</script>

templates/common/header.html
{% load static %}
<header class="blog-header py-3">
    <div class="top-head left">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4 col-lg-4 text-center">
                </div>
                <div class="col-md-6 col-lg-4 text-center">
                    <a class="blog-header-logo text-dark" href="{% url 'locator:home' %}"><img src="{% static 'images/logo_text.png' %}" title="Zeshastyles" alt="zeshastyles" style="width:90%"></a>
                </div>
                <div class="col-4 d-flex navigation-search">
                    <form class="ml-auto" action="/search/" method="get">
                        <input type="text" class="textbox" placeholder="Search" name="q" />
                        <input title="Search" value="" type="submit" class="search-button button">
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

templates/common/side_menu.html
{% load static %}
{% load products %}
<div class="page-wrapper chiller-theme">
    <a id="show-sidebar" class="btn btn-sm btn-danger" href="javascript:void;">
            <i class="fas fa-bars"></i>
        </a>
    <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
            <div class="sidebar-brand">
                <a class="blog-header-logo text-dark" href="{% url 'locator:home' %}"><img src="{% static 'images/logo.png' %}" title="Online shopping site for best deals, coupons. Shop best  Women Clothing, Shoes, Home &  Accessories online on Zeshastyles across world." alt="zeshastyles"></a>
                <div id="close-sidebar">
                    <i class="fas fa-times"></i>
                </div>
            </div>
            <!-- sidebar-header  -->
            <!-- <div class="sidebar-search">
                <div>
                    <div class="input-group">
                        <input type="text" class="form-control search-menu" placeholder="Search...">
                        <div class="input-group-append">
                            <span class="input-group-text">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </span>
                        </div>
                    </div>
                </div>
            </div> -->
            <!-- sidebar-search  -->
            <div class="sidebar-menu">
                <ul>
                    <li class="header-menu">
                        <span>Product</span>
                    </li>
                    {% for category in categories %}
                    <li class="sidebar-dropdown">
                        <a href="javascript:void;">
                                <!-- <i class="fa fa-tachometer-alt"></i> -->
                                <span>{{category.name}}</span>
                                <!-- <span class="badge badge-pill badge-danger">New</span> -->
                            </a>
                        <div class="sidebar-submenu">
                            <ul>
                                {% for children in category.children.all %}
                                {% if children.slug and not children.disabled %}
                                <li>
                                    <a href='{% url "locator:category_products" children.slug %}'>{{children.name|checkName}}
                                            <!-- <span class="badge badge-pill badge-success">Pro</span> -->
                                        </a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                    {% endfor %}
                    <li class="header-menu">
                        <span>Articles</span>
                    </li>
                    <li>
                        <a href="{% url 'blog:post_list' %}">
                                <!-- <i class="fa fa-book"></i> -->
                                <span>Fashion Articles & News</span>
                            </a>
                    </li>
                </ul>
            </div>
            <!-- sidebar-menu  -->
        </div>
        <!-- sidebar-content  -->
        <div class="sidebar-footer">
            <a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/zeshastyles/"><i id="social-fb" class="fab fa-facebook-square fa-1x social"></i></a>
            <a target="_blank" rel="noopener noreferrer" href="https://plus.google.com/u/0/106725238703021839319"><i id="social-fb" class="fab fa-google-plus-g fa-1x social"></i></a>
            <a target="_blank" rel="noopener noreferrer" href="https://twitter.com/zeshastyles"><i id="social-fb" class="fab fa-twitter fa-1x social"></i></a>
            <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/company/zeshastyles/"><i class="fab fa-linkedin-in fa-1x social"></i></a>
            <a target="_blank" rel="noopener noreferrer" href="https://in.pinterest.com/Zeshastyles/"><i class="fab fa-pinterest fa-1x social"></i></a>
            <a target="_blank" rel="noopener noreferrer" href="https://zeshastyles.tumblr.com/"><i class="fab fa-tumblr fa-1x social"></i></a>
        </div>
    </nav>
</div>